import{S as m}from"./assets/vendor-D0gBiHs0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const d="48488586-a0a2593ae7f5d81beed47469e",h="https://pixabay.com/api/";async function y(o,r,n){const s=`${h}? key=${d}&q=${encodeURLComponent(o)}$image_type=photo=${n}`,e=await fetch(s);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}function g({webformatURL:o,largeImageURL:r,tags:n,likes:s,views:e,comments:t,downloads:i}){return`
    <a href="${r}" class="gallery-item">
        <img src="${o}" alt="${n}" loading="lazy" />
        <div class="info">
          <p class="info-item"><span>Likes</span><b>${s}</b></p>
          <p class="info-item"><span>Views</span><b>${e}</b></p>
          <p class="info-item"><span>Comments</span><b>${t}</b></p>
          <p class="info-item"><span>Downloads</span><b>${i}</b></p>
        </div>
      </a>
      `}const b=document.querySelector("#search-form"),p=document.querySelector(".gallery"),f=document.querySelector(".loader");let a="",c=1;const L=40;let l;b.addEventListener("submit",P);function w(){f.style.display="block"}function u(){f.style.display="none"}function $(){iziToast.error({title:"",message:"Sorry, there are no images matching<br>your search query. Please, try again!",position:"topRight",timeout:5e3,backgroundColor:"#f14646",class:"custom-toast"})}function P(o){o.preventDefault();const r=o.currentTarget.elements.searchQuery.value.trim();if(!r){iziToast.error({title:"Error",message:"Please enter a search query.",position:"topRight",timeout:3e3});return}a=r,c=1,q(),w(),y(a,c,L).then(n=>{setTimeout(()=>{if(u(),n.hits.length===0){$();return}S(n.hits),l=new m(".gallery a"),l.refresh()},2e3)}).catch(()=>{u(),iziToast.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight",timeout:3e3})})}function S(o){const r=o.map(g).join("");p.insertAdjacentHTML("beforeend",r)}function q(){p.innerHTML=""}
//# sourceMappingURL=index.js.map
